apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: source-vm
spec:
  clusterIP: None
  selector:
    app: source-vm
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: source-vm
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
